In [1]:
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(networkD3)
library(tibble)
library(ggalluvial)
library(RColorBrewer)
library(scales)
library(viridis)
library(readr)

Warning message:
“package ‘readxl’ was built under R version 4.3.3”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
Warning message:
“package ‘networkD3’ was built under R version 4.3.3”
Warning message:
“package ‘ggalluvial’ was built under R version 4.3.3”
Warning message:
“package ‘scales’ was built under R version 4.3.3”
Warning message:
“package ‘viridis’ was built under R version 4.3.3”
Loading required package: viridisLite


Attaching package: ‘viridis’


The following object is masked from ‘package:scales’:

    viridis_pal



Attaching package: ‘readr’


The following object is masked from ‘package:scales’:

    col_factor

In [2]:
# metabolite <- readRDS("/vol/projects/yzhang/500FG_aging/input/metabolite/metabolite_trans.rds")
# head(metabolite)
# dim(metabolite)

      Deoxynivalenol Xenognosin A 1-(4-Hydroxy-3-methoxyphenyl)-3-decanone
HV001 20325.5        16030.5      388846.0
HV002 20604.5        18831.5      324465.0
HV003 30331.0        24791.5      331666.5
HV004 14997.0        17869.5      374568.5
HV005 13991.0        15543.5      318622.0
HV006 15048.5        17714.5      387658.5
      Cymarose Digitalose 2-Naphthol
HV001 10987.5  14547.0    21882.5
HV002  9602.0  12737.0    19354.5
HV003  9588.0  13865.5    17533.0
HV004  9072.5  13150.0    20510.5
HV005  8679.5  13636.5    18029.0
HV006  9029.5  13891.5    21299.0
      5-Hydroxy-7-(4-hydroxy-3-methoxyphenyl)-1-phenyl-3-heptanone
HV001 14201.0
HV002 20310.0
HV003 19598.0
HV004 18216.5
HV005 19823.5
HV006 20080.0
      N,N'-Diacetylchitobiosyldiphosphodolichol 10-Undecenal Vitamin A ⋯
HV001 14650.5                                   8620.5       11428     ⋯
HV002 14790.0                                   8081.0       14077     ⋯
HV003 14537.0                                   7405.0       11285     ⋯
HV004 16288.0                                   7810.0       12780     ⋯
HV005 14830.5                                   8571.0       15183     ⋯
HV006 15122.5                                   7532.0       11903     ⋯
      Dihydroisomorphine-3-glucuronide
HV001 13142.5
HV002 11661.0
HV003 20263.0
HV004 15027.5
HV005 36945.0
HV006 29487.0
      7,11-Bisdeacetylvaltrate 7-(3-methylpentanoate) 11-(3-hydroxy-3-methylbutanoate)
HV001 14167.0
HV002 34008.5
HV003 14685.0
HV004 12052.0
HV005 13568.5
HV006 13197.5
      (7'x,8'x)-4,7'-Epoxy-3,8'-bilign-7-ene-3,5'-dimethoxy-4',9,9'-triol,3-(4-hydroxyphenyl)-1-[2,4,6-trihydroxy-3-(4-hydroxy-3-methylbut-2-en-1-yl)phenyl]propan-1-one
HV001  9401.5
HV002  9580.5
HV003 23445.5
HV004  9388.5
HV005 12124.0
HV006 10096.5
      DG(15:0/18:0/0:0) DG(15:0/20:3(5Z,8Z,11Z)/0:0)
HV001 17702.5           17702.5
HV002 16853.5           16853.5
HV003 20627.5           20627.5
HV004 16298.0           16298.0
HV005 35662.5           35662.5
HV006 16939.0           16939.0
      1alpha,3beta,22R-Trihydroxyergosta-5,24E-Dien-26-OicAcid3-O-B-D-Glucoside26-O-B-D-Glucosyl Ester
HV001 10169.5
HV002 13238.5
HV003 15032.5
HV004 12874.0
HV005 16768.0
HV006 13932.5
      Cyanidin 3-O-[b-D-Xylopyranosyl-(1->2)-[(4-hydroxybenzoyl)-(->6)-b-D-glucopyranoside]
HV001 17017.0
HV002 18201.0
HV003 15631.5
HV004 18982.0
HV005 16786.5
HV006 15564.0
      TG(18:3(9Z,12Z,15Z)/14:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z))[iso6]
HV001 19663.0
HV002 20731.0
HV003 23595.0
HV004 21619.5
HV005 19816.5
HV006 18517.0
      Araliasaponin II Quinic acid
HV001 30233.5          126298.0
HV002 35445.0           60949.5
HV003 36253.0           48469.0
HV004 34825.5           63373.0
HV005 35610.5           42202.5
HV006 33008.5          272100.0

[1]  458 1596

In [3]:
metabolite <- read_tsv("/vol/projects/CIIM/cohorts_old/500FG/metabolic/500FG raw metabolite_fromJianbo.tsv")
head(metabolite)
dim(metabolite)
metabolite_num <- metabolite[,c(22:479)]
metabolite_num <- as.data.frame(metabolite_num)
rownames(metabolite_num) <- metabolite$ metabolite_identification
head(metabolite_num)
dim(metabolite_num)
any(is.na(metabolite_num))
# 转置 cytokine_filter 数据框
metabolite_trans <- as.data.frame(t(metabolite_num))
colnames(metabolite_trans) <- rownames(metabolite_num)
rownames(metabolite_trans) <- colnames(metabolite_num)
dim(metabolite_trans)
head(metabolite_trans)

Rows: 1596 Columns: 479
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr   (5): database_identifier, chemical_formula, smiles, inchi, metabolite_...
dbl (460): mass_to_charge, reliability, HV001, HV002, HV003, HV004, HV005, H...
lgl  (14): fragmentation, modifications, charge, retention_time, taxid, spec...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  database_identifier chemical_formula
1 CHEBI:10022         C15H20O6
2 CHEBI:10075         C16H16O3
3 CHEBI:10137         C17H26O3
4 CHEBI:10366         C7H14O4
5 CHEBI:10368         C7H14O5
6 CHEBI:10432         C10H8O
  smiles
1 [H][C@@]12O[C@]3([H])C=C(C)C(=O)[C@@H](O)[C@]3(CO)[C@@](C)(C[C@H]1O)[C@]21CO1
2 COc1cc(O)ccc1C\\C=C\\c1ccc(O)cc1
3 CCCCCCCC(=O)CCc1ccc(O)c(OC)c1
4 [H]C([H])(C=O)[C@]([H])(OC)[C@]([H])(O)[C@@]([H])(C)O
5 [H][C@](C)(O)[C@]([H])(O)[C@]([H])(OC)[C@@]([H])(O)C=O
6 Oc1ccc2ccccc2c1
  inchi
1 InChI=1S/C15H20O6/c1-7-3-9-14(5-16,11(19)10(7)18)13(2)4-8(17)12(21-9)15(13)6-20-15/h3,8-9,11-12,16-17,19H,4-6H2,1-2H3/t8-,9-,11-,12-,13-,14-,15+/m1/s1
2 InChI=1S/C16H16O3/c1-19-16-11-15(18)10-7-13(16)4-2-3-12-5-8-14(17)9-6-12/h2-3,5-11,17-18H,4H2,1H3/b3-2+
3 InChI=1S/C17H26O3/c1-3-4-5-6-7-8-15(18)11-9-14-10-12-16(19)17(13-14)20-2/h10,12-13,19H,3-9,11H2,1-2H3
4 InChI=1S/C7H14O4/c1-5(9)7(10)6(11-2)3-4-8/h4-7,9-10H,3H2,1-2H3/t5-,6+,7-/m1/s1
5 InChI=1S/C7H14O5/c1-4(9)6(11)7(12-2)5(10)3-8/h3-7,9-11H,1-2H3/t4-,5+,6+,7-/m1/s1
6 InChI=1S/C10H8O/c11-10-6-5-8-3-1-2-4-9(8)7-10/h1-7,11H
  metabolite_identification                mass_to_charge fragmentation
1 Deoxynivalenol                           295.1191       NA
2 Xenognosin A                             255.1038       NA
3 1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 277.1809       NA
4 Cymarose                                 161.0819       NA
5 Digitalose                               177.0772       NA
6 2-Naphthol                               143.0493       NA
  modifications charge retention_time ⋯ HV525    HV526    HV527    HV528
1 NA            NA     NA             ⋯  18349.0  44987.5  22414.5  19734.0
2 NA            NA     NA             ⋯  17442.5  23112.5  18458.0  15341.0
3 NA            NA     NA             ⋯ 410828.5 424573.0 784687.0 294914.5
4 NA            NA     NA             ⋯  10493.0  10690.0  10907.5   9893.0
5 NA            NA     NA             ⋯  17688.0  14362.5  16077.5  14465.5
6 NA            NA     NA             ⋯  24687.0  20415.5  23917.5  19506.5
  HV529    HV530    HV531    HV532    HV533    HV534
1  21075.5  16550.0  20302.0  12916.5  13331.0  36608.0
2  17501.0  12886.5  13475.0  20116.5  18011.5  18617.5
3 864931.0 356691.0 424070.5 382228.5 465130.0 370595.5
4  11671.5  10216.5  11271.0  10342.5  10849.5   9935.5
5  19710.0  14843.5  14253.5  15513.0  13962.5  13581.0
6  20907.0  18360.0  18922.0  19580.0  17712.0  16752.5

[1] 1596  479

                                         HV001    HV002    HV003    HV004
Deoxynivalenol                            20325.5  20604.5  30331.0  14997.0
Xenognosin A                              16030.5  18831.5  24791.5  17869.5
1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 388846.0 324465.0 331666.5 374568.5
Cymarose                                  10987.5   9602.0   9588.0   9072.5
Digitalose                                14547.0  12737.0  13865.5  13150.0
2-Naphthol                                21882.5  19354.5  17533.0  20510.5
                                         HV005    HV006    HV007    HV008
Deoxynivalenol                            13991.0  15048.5  17086.0  19065.5
Xenognosin A                              15543.5  17714.5  14684.5  16868.0
1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 318622.0 387658.5 434873.0 400345.5
Cymarose                                   8679.5   9029.5  10611.0   9393.0
Digitalose                                13636.5  13891.5  15179.5  12754.5
2-Naphthol                                18029.0  21299.0  21016.5  21188.5
                                         HV009    HV011    ⋯ HV525    HV526
Deoxynivalenol                            36626.5  20855.0 ⋯  18349.0  44987.5
Xenognosin A                              16668.0  16151.0 ⋯  17442.5  23112.5
1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 276148.0 258801.0 ⋯ 410828.5 424573.0
Cymarose                                   9817.0   9269.5 ⋯  10493.0  10690.0
Digitalose                                13344.0  14238.0 ⋯  17688.0  14362.5
2-Naphthol                                18381.5  19498.5 ⋯  24687.0  20415.5
                                         HV527    HV528    HV529    HV530
Deoxynivalenol                            22414.5  19734.0  21075.5  16550.0
Xenognosin A                              18458.0  15341.0  17501.0  12886.5
1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 784687.0 294914.5 864931.0 356691.0
Cymarose                                  10907.5   9893.0  11671.5  10216.5
Digitalose                                16077.5  14465.5  19710.0  14843.5
2-Naphthol                                23917.5  19506.5  20907.0  18360.0
                                         HV531    HV532    HV533    HV534
Deoxynivalenol                            20302.0  12916.5  13331.0  36608.0
Xenognosin A                              13475.0  20116.5  18011.5  18617.5
1-(4-Hydroxy-3-methoxyphenyl)-3-decanone 424070.5 382228.5 465130.0 370595.5
Cymarose                                  11271.0  10342.5  10849.5   9935.5
Digitalose                                14253.5  15513.0  13962.5  13581.0
2-Naphthol                                18922.0  19580.0  17712.0  16752.5

[1] 1596  458

[1] FALSE

[1]  458 1596

      Deoxynivalenol Xenognosin A 1-(4-Hydroxy-3-methoxyphenyl)-3-decanone
HV001 20325.5        16030.5      388846.0
HV002 20604.5        18831.5      324465.0
HV003 30331.0        24791.5      331666.5
HV004 14997.0        17869.5      374568.5
HV005 13991.0        15543.5      318622.0
HV006 15048.5        17714.5      387658.5
      Cymarose Digitalose 2-Naphthol
HV001 10987.5  14547.0    21882.5
HV002  9602.0  12737.0    19354.5
HV003  9588.0  13865.5    17533.0
HV004  9072.5  13150.0    20510.5
HV005  8679.5  13636.5    18029.0
HV006  9029.5  13891.5    21299.0
      5-Hydroxy-7-(4-hydroxy-3-methoxyphenyl)-1-phenyl-3-heptanone
HV001 14201.0
HV002 20310.0
HV003 19598.0
HV004 18216.5
HV005 19823.5
HV006 20080.0
      N,N'-Diacetylchitobiosyldiphosphodolichol 10-Undecenal Vitamin A ⋯
HV001 14650.5                                   8620.5       11428     ⋯
HV002 14790.0                                   8081.0       14077     ⋯
HV003 14537.0                                   7405.0       11285     ⋯
HV004 16288.0                                   7810.0       12780     ⋯
HV005 14830.5                                   8571.0       15183     ⋯
HV006 15122.5                                   7532.0       11903     ⋯
      Dihydroisomorphine-3-glucuronide
HV001 13142.5
HV002 11661.0
HV003 20263.0
HV004 15027.5
HV005 36945.0
HV006 29487.0
      7,11-Bisdeacetylvaltrate 7-(3-methylpentanoate) 11-(3-hydroxy-3-methylbutanoate)
HV001 14167.0
HV002 34008.5
HV003 14685.0
HV004 12052.0
HV005 13568.5
HV006 13197.5
      (7'x,8'x)-4,7'-Epoxy-3,8'-bilign-7-ene-3,5'-dimethoxy-4',9,9'-triol,3-(4-hydroxyphenyl)-1-[2,4,6-trihydroxy-3-(4-hydroxy-3-methylbut-2-en-1-yl)phenyl]propan-1-one
HV001  9401.5
HV002  9580.5
HV003 23445.5
HV004  9388.5
HV005 12124.0
HV006 10096.5
      DG(15:0/18:0/0:0) DG(15:0/20:3(5Z,8Z,11Z)/0:0)
HV001 17702.5           17702.5
HV002 16853.5           16853.5
HV003 20627.5           20627.5
HV004 16298.0           16298.0
HV005 35662.5           35662.5
HV006 16939.0           16939.0
      1alpha,3beta,22R-Trihydroxyergosta-5,24E-Dien-26-OicAcid3-O-B-D-Glucoside26-O-B-D-Glucosyl Ester
HV001 10169.5
HV002 13238.5
HV003 15032.5
HV004 12874.0
HV005 16768.0
HV006 13932.5
      Cyanidin 3-O-[b-D-Xylopyranosyl-(1->2)-[(4-hydroxybenzoyl)-(->6)-b-D-glucopyranoside]
HV001 17017.0
HV002 18201.0
HV003 15631.5
HV004 18982.0
HV005 16786.5
HV006 15564.0
      TG(18:3(9Z,12Z,15Z)/14:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z))[iso6]
HV001 19663.0
HV002 20731.0
HV003 23595.0
HV004 21619.5
HV005 19816.5
HV006 18517.0
      Araliasaponin II Quinic acid
HV001 30233.5          126298.0
HV002 35445.0           60949.5
HV003 36253.0           48469.0
HV004 34825.5           63373.0
HV005 35610.5           42202.5
HV006 33008.5          272100.0

In [10]:
basicPhenos = read.csv("/vol/projects/yzhang/500FG_aging/output/02_Olink/Age_group_basicPhenos.csv",row.names=1)
rownames(basicPhenos) = basicPhenos$ID_500fg

## Filter a feature matrix and phenotype table to shared sample IDs and align rows in the same order
prep_filter_match <- function(feature_mat, basicPhenos) {
  idx <- intersect(rownames(feature_mat), rownames(basicPhenos))
  feature_filter <- feature_mat[idx, , drop = FALSE]
  pheno_match <- basicPhenos[rownames(feature_filter), , drop = FALSE]
  list(feature_filter = feature_filter, basicPhenos_filter_match = pheno_match)
}
# usage
res <- prep_filter_match(metabolite_trans, basicPhenos)
metabolite_filter <- res$feature_filter
basicPhenos_filter_match <- res$basicPhenos_filter_match
##one missing gender value
basicPhenos_filter_match$Gender <- trimws(basicPhenos_filter_match$Gender)
basicPhenos_filter_match$Gender[basicPhenos_filter_match$Gender == ""] <- NA


head(metabolite_filter)
dim(metabolite_filter)
head(basicPhenos_filter_match)
dim(basicPhenos_filter_match)

      Deoxynivalenol Xenognosin A 1-(4-Hydroxy-3-methoxyphenyl)-3-decanone
HV001 20325.5        16030.5      388846.0
HV002 20604.5        18831.5      324465.0
HV003 30331.0        24791.5      331666.5
HV004 14997.0        17869.5      374568.5
HV005 13991.0        15543.5      318622.0
HV006 15048.5        17714.5      387658.5
      Cymarose Digitalose 2-Naphthol
HV001 10987.5  14547.0    21882.5
HV002  9602.0  12737.0    19354.5
HV003  9588.0  13865.5    17533.0
HV004  9072.5  13150.0    20510.5
HV005  8679.5  13636.5    18029.0
HV006  9029.5  13891.5    21299.0
      5-Hydroxy-7-(4-hydroxy-3-methoxyphenyl)-1-phenyl-3-heptanone
HV001 14201.0
HV002 20310.0
HV003 19598.0
HV004 18216.5
HV005 19823.5
HV006 20080.0
      N,N'-Diacetylchitobiosyldiphosphodolichol 10-Undecenal Vitamin A ⋯
HV001 14650.5                                   8620.5       11428     ⋯
HV002 14790.0                                   8081.0       14077     ⋯
HV003 14537.0                                   7405.0       11285     ⋯
HV004 16288.0                                   7810.0       12780     ⋯
HV005 14830.5                                   8571.0       15183     ⋯
HV006 15122.5                                   7532.0       11903     ⋯
      Dihydroisomorphine-3-glucuronide
HV001 13142.5
HV002 11661.0
HV003 20263.0
HV004 15027.5
HV005 36945.0
HV006 29487.0
      7,11-Bisdeacetylvaltrate 7-(3-methylpentanoate) 11-(3-hydroxy-3-methylbutanoate)
HV001 14167.0
HV002 34008.5
HV003 14685.0
HV004 12052.0
HV005 13568.5
HV006 13197.5
      (7'x,8'x)-4,7'-Epoxy-3,8'-bilign-7-ene-3,5'-dimethoxy-4',9,9'-triol,3-(4-hydroxyphenyl)-1-[2,4,6-trihydroxy-3-(4-hydroxy-3-methylbut-2-en-1-yl)phenyl]propan-1-one
HV001  9401.5
HV002  9580.5
HV003 23445.5
HV004  9388.5
HV005 12124.0
HV006 10096.5
      DG(15:0/18:0/0:0) DG(15:0/20:3(5Z,8Z,11Z)/0:0)
HV001 17702.5           17702.5
HV002 16853.5           16853.5
HV003 20627.5           20627.5
HV004 16298.0           16298.0
HV005 35662.5           35662.5
HV006 16939.0           16939.0
      1alpha,3beta,22R-Trihydroxyergosta-5,24E-Dien-26-OicAcid3-O-B-D-Glucoside26-O-B-D-Glucosyl Ester
HV001 10169.5
HV002 13238.5
HV003 15032.5
HV004 12874.0
HV005 16768.0
HV006 13932.5
      Cyanidin 3-O-[b-D-Xylopyranosyl-(1->2)-[(4-hydroxybenzoyl)-(->6)-b-D-glucopyranoside]
HV001 17017.0
HV002 18201.0
HV003 15631.5
HV004 18982.0
HV005 16786.5
HV006 15564.0
      TG(18:3(9Z,12Z,15Z)/14:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z))[iso6]
HV001 19663.0
HV002 20731.0
HV003 23595.0
HV004 21619.5
HV005 19816.5
HV006 18517.0
      Araliasaponin II Quinic acid
HV001 30233.5          126298.0
HV002 35445.0           60949.5
HV003 36253.0           48469.0
HV004 34825.5           63373.0
HV005 35610.5           42202.5
HV006 33008.5          272100.0

[1]  451 1596

      ID_500fg Gender Age Height Weight BMI      LivingSituation
HV001 HV001    male   27  178    70     22.09317 Married
HV002 HV002    male   26  178    68     21.46194 Cohabitation
HV003 HV003    female 24  173    68     22.72044 Married
HV004 HV004    female 20  173    65     21.71807 Married
HV005 HV005    female 22  178    64     20.19947 Married
HV006 HV006    female 24  168    58     20.54989 Married
      Education          Ethnicity FarmAnimal   Pets Travel DayInMonth
HV001 University degree  European  Once a month Yes  No     24
HV002 University degree  European  Rarely       No   Yes    24
HV003 University degree  European  Rarely       Yes  Yes    26
HV004 University degree  European  Rarely       Yes  No     26
HV005 University student European  Once a month Yes  Yes     5
HV006 University degree  European  Rarely       Yes  No     NA
      monthinYear dayInYear year AgeGroup
HV001  7          204       2013 Group 5
HV002  7          204       2013 Group 4
HV003  8          236       2013 Group 4
HV004  8          236       2013 Group 2
HV005  9          245       2013 Group 3
HV006 NA           NA         NA Group 4

[1] 451  17

In [11]:
####model 2: age + protein using FDR age not scale + gender
all_results <- list()

for (i in seq_len(ncol(metabolite_filter))) {

  # Build a minimal modeling table
  data <- data.frame(
    feature = log(metabolite_filter[, i] + 1),
    age = basicPhenos_filter_match$Age,
    Gender = factor(basicPhenos_filter_match$Gender)  # convert chr to factor
  )

  # Linear regression
  mod <- lm(feature ~ age + Gender, data = data)

  # Extract coefficient and p-value for age (not Gender)
  cf <- summary(mod)$coefficients
  res <- cf["age", c("Estimate", "Pr(>|t|)")]

  # Store results
  result <- data.frame(
    feature  = colnames(metabolite_filter)[i],
    estimate = res["Estimate"],
    p        = res["Pr(>|t|)"]
  )

  # Signed -log10(p)
  result$value <- -log10(result$p) * result$estimate

  all_results[[i]] <- result
}

final_result <- do.call(rbind, all_results)
final_result$padj <- p.adjust(final_result$p, method = "BH")
final_result$sig <- ifelse(final_result$padj < 0.05, "sig", "no")

head(final_result)
dim(final_result)
table(final_result$sig)
write.csv(final_result, file = "/vol/projects/yzhang/500FG_aging/output/03_metabolite/metabolite_age_linear_gender_FDR.csv")

          feature                                  estimate      p
Estimate  Deoxynivalenol                           -0.0021935538 1.463405e-02
Estimate1 Xenognosin A                              0.0043140324 1.653234e-08
Estimate2 1-(4-Hydroxy-3-methoxyphenyl)-3-decanone -0.0022477068 8.116900e-02
Estimate3 Cymarose                                  0.0002078031 6.635199e-01
Estimate4 Digitalose                                0.0009722504 7.081403e-02
Estimate5 2-Naphthol                               -0.0009047130 1.127605e-01
          value         padj         sig
Estimate  -4.024372e-03 3.879725e-02 sig
Estimate1  3.357036e-02 2.748502e-07 sig
Estimate2 -2.451371e-03 1.577902e-01 no
Estimate3  3.701929e-05 7.537209e-01 no
Estimate4  1.117972e-03 1.407462e-01 no
Estimate5 -8.575259e-04 2.036774e-01 no

[1] 1596    6

 no sig
971 625

In [9]:
save.image("/vol/projects/yzhang/500FG_aging/output/03_metabolite/metabolite_gender.Rdata")

In [2]:
load("/vol/projects/yzhang/500FG_aging/output/03_metabolite/metabolite_gender.Rdata")

In [3]:
final_result_sig <- final_result %>%
  filter(sig == "sig") %>%
  select(feature, estimate, p, padj)
head(final_result_sig)
dim(final_result_sig)
write_excel_csv(final_result_sig,"/vol/projects/yzhang/500FG_aging/output/03_metabolite/metabolite_age_linear_gender_FDR_sig.csv")

           feature                   estimate     p            padj
Estimate   Deoxynivalenol            -0.002193554 1.463405e-02 3.879725e-02
Estimate1  Xenognosin A               0.004314032 1.653234e-08 2.748502e-07
Estimate8  10-Undecenal              -0.001547591 5.039188e-05 2.872337e-04
Estimate10 LysoPE(0:0/20:0)           0.003684064 4.252888e-06 3.294956e-05
Estimate11 LysoPE(0:0/20:2(11Z,14Z)) -0.002515251 1.505447e-02 3.977969e-02
Estimate13 Hippurate                  0.009687998 3.426719e-05 2.018097e-04

[1] 625   4