In [1]:
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(networkD3)
library(tibble)
library(ggalluvial)
library(RColorBrewer)
library(scales)
library(viridis)
library(readr)

Warning message:
“package ‘readxl’ was built under R version 4.3.3”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
Warning message:
“package ‘networkD3’ was built under R version 4.3.3”
Warning message:
“package ‘ggalluvial’ was built under R version 4.3.3”
Warning message:
“package ‘scales’ was built under R version 4.3.3”
Warning message:
“package ‘viridis’ was built under R version 4.3.3”
Loading required package: viridisLite


Attaching package: ‘viridis’


The following object is masked from ‘package:scales’:

    viridis_pal



Attaching package: ‘readr’


The following object is masked from ‘package:scales’:

    col_factor

In [2]:
cellCounts = read.csv("/vol/projects/CIIM/cohorts_old/500FG/Molecular_phenotype/500FG_cellCounts_cellPerc.csv",row.names=1)
head(cellCounts)
cellCounts_select = read.table("/vol/projects/CIIM/cohorts_old/500FG/Molecular_phenotype/500FG_inverse_rank_normalized_cellcounts.txt", header = TRUE, stringsAsFactors = FALSE) ##less
head(cellCounts_select)
dim(cellCounts_select)
cellCounts <- cellCounts[,colnames(cellCounts) %in% colnames(cellCounts_select)]
head(cellCounts)
dim(cellCounts)
any(is.na(cellCounts))

      IT1      IT2    IT3    IT4   IT5   IT6     IT7     IT8    IT9    IT11   ⋯
HV003  3037075 338003 266556 37873 21738 1283869  997227  39248  55644 132535 ⋯
HV004 12837180 534745 455914 31178 18441 1960252 1214855 439036  44759 169069 ⋯
HV006  3155740 253856 212280 19859 10034 1681848 1262400 155528  76864 145687 ⋯
HV007  2877976 230940 196798 16245 12205 1223816  793042 222175  25083  72128 ⋯
HV008  3378569 307137 243099 19421 15310 1444715 1067657 129387 102714  74729 ⋯
HV012  2357939 355273 282569 29434 26797 2370438 1692438 366060  63943 126161 ⋯
      IT209     IT210      IT211       IT212        IT213       IT214
HV003  9.040527 0.07209519 0.004963328 0.0010208037 0.037761479 0.007766374
HV004 11.974640 0.05817235 0.004506337 0.0008555986 0.023997141 0.004556232
HV006  6.433164 0.05743766 0.002618931 0.0007687970 0.022363485 0.006564885
HV007 11.047047 0.04907738 0.002692965 0.0006421505 0.023341514 0.005565897
HV008 12.929089 0.04153785 0.001325280 0.0003152580 0.004663773 0.001109419
HV012  4.192742 0.03743869 0.002327464 0.0005257336 0.009639233 0.002177335
      IT215      IT216       IT217      IT218
HV003 0.06958706 0.014311916 0.25001507 0.05142040
HV004 0.07438069 0.014122335 0.23504990 0.04462790
HV006 0.03528763 0.010358816 0.14387069 0.04223378
HV007 0.02711241 0.006465086 0.15589729 0.03717447
HV008 0.07441804 0.017702579 0.09727829 0.02314058
HV012 0.05261497 0.011884807 0.10577163 0.02389197

      IT1        IT2        IT3        IT4        IT5        IT7
HV003 -0.7045564 -0.4783576 -0.3823108 -0.0522959 -0.1945046 -1.1736302
HV004  2.4682104  0.3433585  0.5761697 -0.3614678 -0.4783576 -0.6615738
HV005  0.2118786 -1.3576090 -1.2549268 -0.5963799 -0.7553342 -0.3927943
HV006 -0.6435248 -0.9982921 -0.8014168 -1.0818022 -1.4626983 -0.5336287
HV007 -0.8632995 -1.1736302 -0.8562626 -1.3824671 -1.0994290 -1.6994536
HV008 -0.4620647 -0.6375551 -0.5733018 -1.1083718 -0.7880801 -0.9982921
      IT8        IT9         IT11        IT12       ⋯ IT84       IT85
HV003 -2.8877786 -0.32023844  0.01580384 -0.8775032 ⋯ -0.1304413  0.41124576
HV004  1.0267065 -0.57904232  0.41124576 -0.5848020 ⋯  0.4920324  0.89551086
HV005  0.1230887  0.98635829  0.75857199 -0.8081388 ⋯  1.0267065  0.04986147
HV006 -0.6080384  0.01094088  0.15746453 -0.4458936 ⋯ -0.5963799  0.19202751
HV007 -0.1206393 -1.27659327 -1.12652869 -1.6791979 ⋯ -1.5219124 -0.29474822
HV008 -0.9361896  0.40068536 -1.08180216 -0.8148976 ⋯  0.1821308 -0.85626255
      IT86        IT87        IT88       IT89       IT90       IT93
HV003 -0.16485366 -0.12063932  0.3023744 -0.7108026 -1.4626983 -0.6798409
HV004 -0.06690952 -0.14025590  0.2218351 -0.3823108 -0.5336287  0.1623896
HV005 -0.46748183  0.21685414 -0.2593771 -0.2543515 -1.1736302 -0.6021990
HV006 -1.60437056 -1.25492680 -1.0308337 -1.5375801 -1.7648168 -0.3718691
HV007 -2.15658740 -2.10931320 -1.3824671 -2.4200373 -2.5228989 -1.2338339
HV008  0.12308870 -0.00850951  0.1771891  0.1084030 -0.1994624 -0.4458936
      IT94       IT95
HV003 -0.9590444  0.1673187
HV004  0.1623896  0.2468250
HV005 -0.6859803  0.2019431
HV006 -0.6525227 -0.6021990
HV007 -2.3377804 -1.1174042
HV008  0.3485208 -1.0391412

[1] 515  73

      IT1      IT2    IT3    IT4   IT5   IT7     IT8    IT9    IT11   IT12    ⋯
HV003  3037075 338003 266556 37873 21738  997227  39248  55644 132535  723938 ⋯
HV004 12837180 534745 455914 31178 18441 1214855 439036  44759 169069  794381 ⋯
HV006  3155740 253856 212280 19859 10034 1262400 155528  76864 145687  849018 ⋯
HV007  2877976 230940 196798 16245 12205  793042 222175  25083  72128  501653 ⋯
HV008  3378569 307137 243099 19421 15310 1067657 129387 102714  74729  733645 ⋯
HV012  2357939 355273 282569 29434 26797 1692438 366060  63943 126161 1072019 ⋯
      IT84  IT85  IT86  IT87 IT88  IT89  IT90 IT93  IT94 IT95
HV003 17315 62210 35380 3931 24204 15108 3507 11871 2158 16842
HV004 27053 85490 36540 3911 22572 17879 5978 20728 4023 18046
HV006 13245 54001 16797 2046  9174  9669 2937 14190 2508  9702
HV007  7269 41797 10213 1135  5793  5554 1732  9257 1075  7047
HV008 22068 28847 40343 4177 21990 22530 7002 13734 4422  7322
HV012 26517 53307 36401 4139 16778 23762 5432 18810 5395  9387

[1] 515  73

[1] FALSE

In [10]:
basicPhenos = read.csv("/vol/projects/yzhang/500FG_aging/output/02_Olink/Age_group_basicPhenos.csv")
rownames(basicPhenos) = basicPhenos$ID_500fg

## Filter a feature matrix and phenotype table to shared sample IDs and align rows in the same order
prep_filter_match <- function(feature_mat, basicPhenos) {
  idx <- rownames(feature_mat)[rownames(feature_mat) %in% rownames(basicPhenos)]  # keep feature_mat order
  feature_filter <- feature_mat[idx, , drop = FALSE]
  pheno_match <- basicPhenos[rownames(feature_filter), , drop = FALSE]
  list(feature_filter = feature_filter, basicPhenos_filter_match = pheno_match)
}
res <- prep_filter_match(cellCounts, basicPhenos)
cellCounts_filter <- res$feature_filter
basicPhenos_filter_match <- res$basicPhenos_filter_match
##one missing gender value
basicPhenos_filter_match$Gender <- trimws(basicPhenos_filter_match$Gender)
basicPhenos_filter_match$Gender[basicPhenos_filter_match$Gender == ""] <- NA

head(cellCounts_filter)
dim(cellCounts_filter)
head(basicPhenos_filter_match)
dim(basicPhenos_filter_match)

      IT1      IT2    IT3    IT4   IT5   IT7     IT8    IT9    IT11   IT12    ⋯
HV003  3037075 338003 266556 37873 21738  997227  39248  55644 132535  723938 ⋯
HV004 12837180 534745 455914 31178 18441 1214855 439036  44759 169069  794381 ⋯
HV006  3155740 253856 212280 19859 10034 1262400 155528  76864 145687  849018 ⋯
HV007  2877976 230940 196798 16245 12205  793042 222175  25083  72128  501653 ⋯
HV008  3378569 307137 243099 19421 15310 1067657 129387 102714  74729  733645 ⋯
HV012  2357939 355273 282569 29434 26797 1692438 366060  63943 126161 1072019 ⋯
      IT84  IT85  IT86  IT87 IT88  IT89  IT90 IT93  IT94 IT95
HV003 17315 62210 35380 3931 24204 15108 3507 11871 2158 16842
HV004 27053 85490 36540 3911 22572 17879 5978 20728 4023 18046
HV006 13245 54001 16797 2046  9174  9669 2937 14190 2508  9702
HV007  7269 41797 10213 1135  5793  5554 1732  9257 1075  7047
HV008 22068 28847 40343 4177 21990 22530 7002 13734 4422  7322
HV012 26517 53307 36401 4139 16778 23762 5432 18810 5395  9387

[1] 508  73

      X   ID_500fg Gender Age Height Weight BMI      LivingSituation
HV003 257 HV003    female 24  173    68     22.72044 Married
HV004 258 HV004    female 20  173    65     21.71807 Married
HV006 530 HV006    female 24  168    58     20.54989 Married
HV007 259 HV007    male   23  192    87     23.60026 Married
HV008 260 HV008    male   25  180    74     22.83951 Single living alone
HV012 261 HV012    female 22  173    61     20.38157 Single living alone
      Education          Ethnicity FarmAnimal   Pets Travel DayInMonth
HV003 University degree  European  Rarely       Yes  Yes    26
HV004 University degree  European  Rarely       Yes  No     26
HV006 University degree  European  Rarely       Yes  No     NA
HV007 University degree  European  Rarely       No   Yes    26
HV008 Primary education  European  Once a month Yes  Yes    26
HV012 University student European  Rarely       No   Yes    26
      monthinYear dayInYear year AgeGroup
HV003  8          236       2013 Group 4
HV004  8          236       2013 Group 2
HV006 NA           NA         NA Group 4
HV007  8          236       2013 Group 3
HV008  8          236       2013 Group 4
HV012  8          236       2013 Group 3

[1] 508  18

In [11]:
####model 2: age + hormone using FDR age not scale + gender
all_results <- list()

for (i in seq_len(ncol(cellCounts_filter))) {

  # Build a minimal modeling table
  data <- data.frame(
    feature =log(cellCounts_filter[, i]+ 1),
    age = basicPhenos_filter_match$Age,
    Gender = factor(basicPhenos_filter_match$Gender)  # convert chr to factor
  )

  # Linear regression
  mod <- lm(feature ~ age + Gender, data = data)

  # Extract coefficient and p-value for age (not Gender)
  cf <- summary(mod)$coefficients
  res <- cf["age", c("Estimate", "Pr(>|t|)")]

  # Store results
  result <- data.frame(
    feature  = colnames(cellCounts_filter)[i],
    estimate = res["Estimate"],
    p        = res["Pr(>|t|)"]
  )

  # Signed -log10(p)
  result$value <- -log10(result$p) * result$estimate

  all_results[[i]] <- result
}

final_result <- do.call(rbind, all_results)
final_result$padj <- p.adjust(final_result$p, method = "BH")
final_result$sig <- ifelse(final_result$padj < 0.05, "sig", "no")
head(final_result)
dim(final_result)

##replace the name
cellcounts_info <- read.table("/vol/projects/CIIM/cohorts_old/500FG/Molecular_phenotype/500FG_cellcounts_info.txt")
head(cellcounts_info)
match_indices <- match(final_result$feature, cellcounts_info$code)
final_result$feature <- cellcounts_info$finalName[match_indices]
head(final_result)
dim(final_result)

write.csv(final_result, file = "/vol/projects/yzhang/500FG_aging/output/07_cellcounts/cellcounts_age_rawless_gender_FDR.csv")
print(table(final_result$sig))

          feature estimate      p            value         padj         sig
Estimate  IT1      0.0053116240 6.575255e-04  1.690205e-02 1.919974e-03 sig
Estimate1 IT2      0.0027371700 1.226924e-01  2.494061e-03 1.722413e-01 no
Estimate2 IT3      0.0003365318 8.606286e-01  2.193657e-05 9.105201e-01 no
Estimate3 IT4      0.0106594533 7.996762e-07  6.499160e-02 3.441537e-06 sig
Estimate4 IT5      0.0112041293 2.481781e-08  8.521005e-02 2.013000e-07 sig
Estimate5 IT7     -0.0056417279 1.308008e-04 -2.190903e-02 4.151505e-04 sig

[1] 73  6

    code index stain   trait                   cluster type
IT1 IT1  1     Stain 1 Neutrophils             Yes     cellCount
IT2 IT2  2     Stain 1 Monocytes (CD14+)       Yes     cellCount
IT3 IT3  3     Stain 1 Monocytes (CD14++CD16-) Yes     cellCount
IT4 IT4  4     Stain 1 Monocytes (CD14++CD16+) Yes     cellCount
IT5 IT5  5     Stain 1 Monocytes (CD14+CD16+)  Yes     cellCount
IT7 IT7  7     Stain 1 Tc (CD3+ CD56-)         Yes     cellCount
    finalName                             finalSubpopulation
IT1 Granulocytes                          White blood cells
IT2 Monocytes (CD14+)                     White blood cells
IT3 Classical monocytes (CD14++CD16-)     Monocytes
IT4 Non-classical monocytes (CD14++CD16+) Monocytes
IT5 Intermediate monocytes (CD14+CD16+)   Monocytes
IT7 T cells (CD3+ CD56-)                  Lymphocytes
    broadSubpopulations parent grandpa FrequencyPlot
IT1 WBC                 NA     NA       1
IT2 WBC                 NA     NA       1
IT3 Monocytes           IT2    IT1     NA
IT4 Monocytes           IT2    IT1     NA
IT5 Monocytes           IT2    IT1     NA
IT7 Lymphocytes         IT21   NA      NA

          feature                               estimate      p
Estimate  Granulocytes                           0.0053116240 6.575255e-04
Estimate1 Monocytes (CD14+)                      0.0027371700 1.226924e-01
Estimate2 Classical monocytes (CD14++CD16-)      0.0003365318 8.606286e-01
Estimate3 Non-classical monocytes (CD14++CD16+)  0.0106594533 7.996762e-07
Estimate4 Intermediate monocytes (CD14+CD16+)    0.0112041293 2.481781e-08
Estimate5 T cells (CD3+ CD56-)                  -0.0056417279 1.308008e-04
          value         padj         sig
Estimate   1.690205e-02 1.919974e-03 sig
Estimate1  2.494061e-03 1.722413e-01 no
Estimate2  2.193657e-05 9.105201e-01 no
Estimate3  6.499160e-02 3.441537e-06 sig
Estimate4  8.521005e-02 2.013000e-07 sig
Estimate5 -2.190903e-02 4.151505e-04 sig

[1] 73  6

 no sig
 31  42

In [12]:
save.image("/vol/projects/yzhang/500FG_aging/output/07_cellcounts/cellcounts_age_lessraw_FDR_namereplace_gender.Rdata")

In [2]:
load("/vol/projects/yzhang/500FG_aging/output/07_cellcounts/cellcounts_age_lessraw_FDR_namereplace_gender.Rdata")

In [3]:
final_result_sig <- final_result %>%
  filter(sig == "sig") %>%
  select(feature, estimate, p, padj)
head(final_result_sig)
dim(final_result_sig)
write_excel_csv(final_result_sig, "/vol/projects/yzhang/500FG_aging/output/07_cellcounts/cellcounts_age_rawless_gender_FDR_sig.csv")

           feature                               estimate     p
Estimate   Granulocytes                           0.005311624 6.575255e-04
Estimate3  Non-classical monocytes (CD14++CD16+)  0.010659453 7.996762e-07
Estimate4  Intermediate monocytes (CD14+CD16+)    0.011204129 2.481781e-08
Estimate5  T cells (CD3+ CD56-)                  -0.005641728 1.308008e-04
Estimate8  B cells (CD19+)                       -0.006113829 1.576612e-03
Estimate10 CD8+ T cells                          -0.010668145 9.747734e-11
           padj
Estimate   1.919974e-03
Estimate3  3.441537e-06
Estimate4  2.013000e-07
Estimate5  4.151505e-04
Estimate8  3.836424e-03
Estimate10 8.894807e-10

[1] 42  4